rules = [
  {
    name = "Infix +"
    pattern = """(?{x << _}).+(?{y << _})"""
    rewrite = """?{x} + ?{y}"""
  }
  {
    name = "Infix -"
    pattern = """(?{x << _}).-(?{y << _})"""
    rewrite = """?{x} - ?{y}"""
  }
  {
    name = "Infix *"
    pattern = """(?{x << _}).*(?{y << _})"""
    rewrite = """?{x} * ?{y}"""
  }
  {
    name = "Infix /"
    pattern = """(?{x << _})./(?{y << _})"""
    rewrite = """?{x} / ?{y}"""
  }
  {
    name = "Test"
    pattern = """
    def `?f1`(): `?t1` =
      def `?f2`(): `?t1` =
        ?{b << _}
      `?f2`()
    """
    rewrite = """
    def `?f1`(): `?t1` =
      `?b`[`?f2` -> `?f1`]
    """
  }
]