rules = [
  {
    name = "Infix +"
    match-ascriptions = true
    pattern = """(?{x := _}).+(?{y := _})"""
    rewrite = """?{x} + ?{y}"""
  }
  {
    name = "Infix -"
    match-ascriptions = true
    pattern = """(?{x := _}).-(?{y := _})"""
    rewrite = """?{x} - ?{y}"""
  }
  {
    name = "Infix *"
    match-ascriptions = true
    pattern = """(?{x := _}).*(?{y := _})"""
    rewrite = """?{x} * ?{y}"""
  }
  {
    name = "Infix /"
    match-ascriptions = true
    pattern = """(?{x := _})./(?{y := _})"""
    rewrite = """?{x} / ?{y}"""
  }
  {
    name = "Inline Helper Function"
    pattern = """
    def `?f1`(): `?t1` =
      def `?f2`(): `?t1` =
        ?{b := _}
      `?f2`()
    """
    rewrite = """
    def `?f1`(): `?t1` =
      `?b`(`?f2` -> `?f1`)
    """
  }
  {
    name="Placeholder Syntax (single param)"
    pattern="""
    (`?x`: String) => `?body`
    """
    rewrite="""
    `?body`(`?x` -> _)
    """
  }
  {
    name="Placeholder Syntax (two params)"
    pattern="""
    (`?acc`: Int, `?x`: String) => `?body`
    """
    rewrite="""
    `?body`(`?acc` -> _, `?x` -> _)
    """
  }
  {
    name="Expand Map to Match"
    pattern="""
    def `?ex`(`?l`: List[Int]): `?t` =
      `?l`.map((`?x`: Int) => `?f`)
    """
    rewrite="""
    def `?ex`(`?l`: List[Int]): `?t` =
      `?l` match
        case Nil => Nil
        case head :: tail =>
          `?f`(`?x` -> head) :: `?ex`(tail)
    """
  }
  # {
  #   name="Equality of Array"
  #   pattern="""
  #   (`?a1`: Array[`?t1`]) == (`?a2`: Array[`?t2`])
  #   """
  # }
]