rules = [
  {
    name = "Infix +"
    match-ascriptions = true
    pattern = """(?{x := _}).+(?{y := _})"""
    rewrite = """?{x} + ?{y}"""
  }
  {
    name = "Infix -"
    match-ascriptions = true
    pattern = """(?{x := _}).-(?{y := _})"""
    rewrite = """?{x} - ?{y}"""
  }
  {
    name = "Infix *"
    match-ascriptions = true
    pattern = """(?{x := _}).*(?{y := _})"""
    rewrite = """?{x} * ?{y}"""
  }
  {
    name = "Infix /"
    match-ascriptions = true
    pattern = """(?{x := _})./(?{y := _})"""
    rewrite = """?{x} / ?{y}"""
  }
  {
    name = "Test"
    match-ascriptions = true
    pattern = """
    def `?f1`(): `?t1` =
      def `?f2`(): `?t1` =
        ?{b := _}
      `?f2`()
    """
    rewrite = """
    def `?f1`(): `?t1` =
      `?b`[`?f2` -> `?f1`]
    """
  }
  {
    name="map"
    match-ascriptions = true
    pattern="""
    def `?ex`(`?l`: List[Int]) =
      `?l`.map((`?x`: Int) => `?f`)
    """
    rewrite="""
    def `?ex`(`?l`: List[Int]): List[Int] =
      `?l` match
        case Nil => Nil
        case head :: tail =>
          `?f`[`?x` -> head] :: `?ex`(tail)
    """
  }
]