rules = [
  {
    name = "Infix"
    description = "Rewrite infix + operator"
    match-ascriptions = true
    pattern = """`?x`.+(`?y`)"""
    rewrite = """`?x` + `?y`"""
  }
  {
    name = "Infix"
    description = "Rewrite infix - operator"
    match-ascriptions = true
    pattern = """`?x`.-(`?y`)"""
    rewrite = """`?x` - `?y`"""
  }
  {
    name = "Infix"
    description = "Rewrite infix * operator"
    match-ascriptions = true
    pattern = """`?x`.*(`?y`)"""
    rewrite = """`?x` * `?y`"""
  }
  {
    name = "Infix"
    description = "Rewrite infix / operator"
    match-ascriptions = true
    pattern = """`?x`./(`?y`)"""
    rewrite = """`?x` / `?y`"""
  }
  {
    name = "If Simplification"
    description = "if c then false else e  ==>  !c && e"
    pattern = """
    if `?c` then false else `?e`
    """
    rewrite = """
    !`?c` && `?e`
    """
  }
  {
    name = "If Simplification"
    description = "if c then e else true  ==>  !c || e"
    pattern = """
    if `?c` then `?e` else true
    """
    rewrite = """
    !`?c` || `?e`
    """
  }
  {
    name = "If Simplification"
    description = "if c then true else e  ==>  c || e"
    pattern = """
    if `?c` then true else `?e`
    """
    rewrite = """
    `?c` || `?e`
    """
  }
  {
    name = "If Simplification"
    description = "if c then e else false  ==>  c && e"
    pattern = """
    if `?c` then `?e` else false
    """
    rewrite = """
    `?c` && `?e`
    """
  }
  {
    name = "Inline Helper Function"
    pattern = """
    def `?f1`(): `?t1` =
      def `?f2`(): `?t1` =
        `?b`
      `?f2`()
    """
    rewrite = """
    def `?f1`(): `?t1` =
      `?b`(`?f2` --> `?f1`)
    """
  } 
  {
    name = "Var Usage"
    description = "Do not use vars - use vals and functional programming instead"
    pattern = """
    var `?v`: `?` = `?init`
    """
  }
  {
    name = "Var Usage"
    description = "Do not use vars - use vals and functional programming instead"
    pattern = """
    var `?v`: `?`
    """
  }
  {
    name = "While Loop"
    description = "Do not use while loops - use HOFs or recursion instead"
    pattern = """
    while (`?cond`) do `?body`
    """
  }
  {
    name = "For Loop"
    description = "Do not use for loops - use HOFs or recursion instead"
    pattern = """
    for (`?v` <- `?iter`) do `?body`
    """
  }
  {
    name = "Predefined Constants"
    description = "Vector2(-1,0) -> Vector2.UnitLeft"
    pattern = """?{+cs214.Vector2(-1,0) | +Vector2(-1,0)}"""
    rewrite = """Vector2.UnitLeft"""
  } 
  {
    name = "Predefined Constants"
    description = "Vector2(1,0) -> Vector2.UnitRight"
    pattern = """?{+cs214.Vector2(1,0) | +Vector2(1,0)}"""
    rewrite = """Vector2.UnitRight"""
  } 
  {
    name = "Predefined Constants"
    description = "Vector2(0,-1) -> Vector2.UnitUp"
    pattern = """?{+cs214.Vector2(0,-1) | +Vector2(0,-1)}"""
    rewrite = """Vector2.UnitUp"""
  } 
  {
    name = "Predefined Constants"
    description = "Vector2(0,1) -> Vector2.UnitDown"
    pattern = """?{+cs214.Vector2(0,1) | +Vector2(0,1)}"""
    rewrite = """Vector2.UnitDown"""
  } 
  {
    name = "Predefined Constants"
    description = "Vector2(0,0) -> Vector2.Zero"
    pattern = """?{+cs214.Vector2(0,0) | +Vector2(0,0)}"""
    rewrite = """Vector2.Zero"""
  } 
  {
    name = "Vector2 Multiplied by Zero"
    description = "v * 0  ==>  Vector2.Zero"
    pattern = """(`?v`: Vector2) * 0"""
    rewrite = """Vector2.Zero"""
  }
  {
    name = "Vector2 Multiplied by Zero"
    description = "0 * v  ==>  Vector2.Zero"
    pattern = """0 * (`?v`: Vector2)"""
    rewrite = """Vector2.Zero"""
  }
  {
    name = "BoidCons Use"
    description = "Use HOFs instead of BoidCons or BoidNil"
    pattern = """
    BoidCons(`?head`, `?tail`)
    """
  }
  {
    name = "BoidNil Use"
    description = "Use HOFs instead of BoidCons or BoidNil"
    pattern = """
    BoidNil()
    """
  }
]