rules = [
  {
    name = "Infix +"
    match-ascriptions = true
    pattern = """(?{x := _}).+(?{y := _})"""
    rewrite = """?{x} + ?{y}"""
  }
  {
    name = "Infix -"
    match-ascriptions = true
    pattern = """(?{x := _}).-(?{y := _})"""
    rewrite = """?{x} - ?{y}"""
  }
  {
    name = "Infix *"
    match-ascriptions = true
    pattern = """(?{x := _}).*(?{y := _})"""
    rewrite = """?{x} * ?{y}"""
  }
  {
    name = "Infix /"
    match-ascriptions = true
    pattern = """(?{x := _})./(?{y := _})"""
    rewrite = """?{x} / ?{y}"""
  }
  {
    name = "If Simplification"
    description = "if c then false else e  ==>  !c && e"
    pattern = """
    if `?c` then false else `?e`
    """
    rewrite = """
    !`?c` && `?e`
    """
  }
  {
    name = "If Simplification"
    description = "if c then e else true  ==>  !c || e"
    pattern = """
    if `?c` then `?e` else true
    """
    rewrite = """
    !`?c` || `?e`
    """
  }
  {
    name = "If Simplification"
    description = "if c then true else e  ==>  c || e"
    pattern = """
    if `?c` then true else `?e`
    """
    rewrite = """
    `?c` || `?e`
    """
  }
  {
    name = "If Simplification"
    description = "if c then e else false  ==>  c && e"
    pattern = """
    if `?c` then `?e` else false
    """
    rewrite = """
    `?c` && `?e`
    """
  }
  {
    name = "Inline Helper Function"
    pattern = """
    def `?f1`(): `?t1` =
      def `?f2`(): `?t1` =
        ?{b := _}
      `?f2`()
    """
    rewrite = """
    def `?f1`(): `?t1` =
      `?b`(`?f2` --> `?f1`)
    """
  } 
  {
    name = "Var Usage"
    description = "Do not use vars - use vals and functional programming instead"
    pattern = """
    var `?v`: `?` = `?init`
    """
  }
  {
    name = "Var Usage"
    description = "Do not use vars - use vals and functional programming instead"
    pattern = """
    var `?v`: `?`
    """
  }
]